### ISSUE TITLE
Provide macOS binaries (was: "exec format error" when trying to execute binary from "releases")

### ISSUE THREAD

**Issue by 4kelly** [jaredkrinke/md2blog#1]
OSX Big Sur

1. Downloaded: md2blog-x86_64-unknown-linux-gnu.zip
2. Extracted ZIP

```
➜  ~ chmod 777 ~/Downloads/md2blog
➜  ~ cd ~/Downloads 
➜  Downloads ./md2blog
zsh: exec format error: ./md2blog
➜  Downloads bash md2blog
md2blog: md2blog: cannot execute binary file
```

Im probably just doing something wrong, but the Deno install worked fine.

**Comment by jaredkrinke** [comment]
It sounds like the issue is that I didn't provide OS X binaries. Deno supports building x64/ARM binaries for Mac, but I have no way of testing them, so I didn't upload them. Maybe I'll just upload them and hope for the best :)

**Comment by 4kelly** [comment]
Happy to test one out for you. Lmk.

**Comment by jaredkrinke** [comment]
Ok, I updated the [release page](https://github.com/jaredkrinke/md2blog/releases/tag/1.0.1) with Mac binaries. Theoretically they should work the same as "deno install", modulo Deno bugs :)

Thanks for all your help!

**Comment by 4kelly** [comment]
Tested and running using the new md2blog-x86_64-apple-darwin.zip. 

However, on OSX you have to explicitly "allow" binaries downloaded through Safari via `System Preferences` `Security & Privacy` menu.

Users will probably receive this prompt. I'm not familiar with ways to mitigate this.

<img width="260" alt="Screen Shot 2021-11-29 at 11 41 40 PM" src="https://user-images.githubusercontent.com/93479011/143986862-69f6d4ce-35dc-41f8-a818-e2a3802a380c.png">

Then in settings:

<img width="648" alt="Screen Shot 2021-11-29 at 11 43 09 PM" src="https://user-images.githubusercontent.com/93479011/143986928-51a2e7e6-d1c6-4c11-8e6d-6a9561214db8.png">

**Comment by jaredkrinke** [comment]
Note to self: I need to update the documentation (after which this can be closed):

* List supported platforms (with caveat that macOS isn't tested)
* Warn about this error on macOS

**Comment by jaredkrinke** [comment]
macOS binaries are now produced by the build script (and I uploaded them for the initial release) and macOS support is documented here:

https://jaredkrinke.github.io/md2blog/posts/faq/platforms.html
https://jaredkrinke.github.io/md2blog/posts/faq/common-problems.html#developer-cannot-be-verified-error-on-macos
