### ISSUE TITLE
Upgrading to 1.1.0 via Deno (command may need updating)

### ISSUE THREAD

**Issue by 4kelly** [jaredkrinke/md2blog#18]
Im not fluent in Deno, and you do warn against this in the docs, but I thought I'd share the changes I had to make to upgrade md2blog. Feel free to resolve if this is expected.

Command from `QuickStart`

`deno install --allow-read --allow-write --allow-net=localhost https://deno.land/x/md2blog/main.ts`

Command I had to run:

`deno install --allow-read --allow-write --allow-net=localhost -f https://deno.land/x/md2blog@1.1.0/main.ts `

Changes:
- add `-f`
- specify version in URL

**Comment by jaredkrinke** [comment]
Hmmm... I didn't think that would be needed. I'll check it out.

**Comment by jaredkrinke** [comment]
`-f` is required to overwrite any previously installed script (and it seems simpler than asking people to uninstall first)

`-r` is needed to re-download the script.

**Comment by jaredkrinke** [comment]
Updated the documentation to add `-r -f`. Thanks for pointing this out!
