### ISSUE TITLE
Provide a way to supply copyright notice for site pages

### ISSUE THREAD

**Issue by jaredkrinke** [jaredkrinke/md2blog#2]
Good suggestion here: https://news.ycombinator.com/item?id=29386873

> Support an optional “footer” argument in ‘site.json’. Useful for copyright, social links, ??

**Comment by 4kelly** [comment]
It's also a useful way to include a default footer:

```json
{
    "md2blog_attribution": true
}
```
> Made with [md2blog](https://jaredkrinke.github.io/md2blog/index.html)

Sorry if I'm ruining the "zero config" dream haha.

**Comment by jaredkrinke** [comment]
Still need to update the template and documentation.

**Comment by jaredkrinke** [comment]
Updates have been committed to md2blog, its documentation, and the template repository. This will be included in the next release:

* https://github.com/jaredkrinke/md2blog/commit/1749a8168fb29d9c97bd3dc07e9c0df70738c03c
* https://github.com/jaredkrinke/md2blog-template-site/commit/f9eae6ca22f98f4807d09721439938e6e333973d
