### ISSUE TITLE
Purple Post titles

### ISSUE THREAD

**Issue by tyeeman** [jaredkrinke/md2blog#47]
Love the purple post titles on your dev site. I don't see a color option for that?

**Comment by jaredkrinke** [comment]
Thanks! A few people have recognized it as (four color) CGA :)

Color options are described here:

https://jaredkrinke.github.io/md2blog/posts/faq/themes.html

Specifically for my site:

https://github.com/jaredkrinke/log/blob/8a3f034cd0ecc104f296397dd7bacea4755fc522/content/site.json#L8

Is that what you were looking for?

**Comment by tyeeman** [comment]
Yes, thanks!

**Comment by jaredkrinke** [comment]
I think this is resolved, so I'm closing it. Feel free to reopen if more is needed.
